set-option -g mouse on
bind-key -n MouseDown1Status select-window -t=
set-option -g status-left "#[fg=white,bg=blue,bold] m:menu #[default] "
set-option -g status-right "#[fg=white] #S"
set-option -g status-justify centre
set-option -g status-style bg=default,fg=white
set-option -g window-status-current-style bg=blue,fg=white,bold
set-option -g window-status-format " #I:#W "
set-option -g window-status-current-format " #I:#W "
