name: Test Examples

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm
        example:
          - name: bind_program
          - name: ebpf
            sudo: true
          - name: enter
          - name: iperf
          - name: nc
          - name: ping
          - name: quiche_perf
          - name: route_metric
          - name: star_topology
          - name: tcpdump
          #- name: chromium # requires display
          #- name: tmux # requires interactive terminal
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v22
      - name: Configure kernel
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      - name: Run ${{ matrix.example.name }}
        run: ${{ matrix.example.sudo && 'sudo $(which nix)' || 'nix' }} run ./examples/${{ matrix.example.name }} --override-input nixnet path:.
